# Generated by Django 3.0.6 on 2020-06-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='hotel_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotels'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=200)),
                ('room_code', models.CharField(max_length=8)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotels')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(default=0, max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Complete'), (1, 'UnComplete')], default=1)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotels')),
                ('menu_items', models.ManyToManyField(to='hotels.Item')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Room')),
            ],
        ),
    ]
