# Generated by Django 3.1.1 on 2021-03-12 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20200609_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('room_no', models.CharField(max_length=200)),
                ('room_code', models.CharField(max_length=8)),
                ('checkin', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out', models.BooleanField(default=False)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('room_no', models.CharField(max_length=200)),
                ('room_code', models.CharField(max_length=8)),
                ('checkin', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out', models.BooleanField(default=False)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels')),
            ],
        ),
    ]
