# Generated by Django 3.1.1 on 2021-03-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_scheduledroom_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledroom',
            name='room_code',
        ),
    ]
