# Generated by Django 3.1.1 on 2021-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_remove_scheduledroom_room_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='room_code',
        ),
        migrations.AddField(
            model_name='scheduledroom',
            name='roomtype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='roomtype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
