# Generated by Django 3.1.1 on 2021-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20210312_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledroom',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='room_no',
        ),
        migrations.AddField(
            model_name='scheduledroom',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scheduledroom',
            name='hotel_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='hotel_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
